<?php
/**
 * @file
 *
 * @author Jon Kamke <jon@ten7.com>
 */

/**
 * Implements hook_block_info().
 */
function rr_toolkits_blocks_block_info() {
  $blocks = array();
  $blocks['rr_toolkit_images'] = array(
    'info' => t('Toolkit images page block'),
    'region' => 'content_top',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'learn-educate/toolkits/images',
  );

  $blocks['rr_toolkit_templates'] = array(
    'info' => t('Toolkit templates page block'),
    'region' => 'content_top',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'learn-educate/toolkits/templates',
  );

  $blocks['rr_toolkit_types'] = array(
    'info' => t('Toolkit tools by type'),
    'region' => 'content_top',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'learn-educate/toolkits',
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function rr_toolkits_blocks_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'rr_toolkit_images':
      $block['content'] = array(
        '#type' => 'markup',
        '#markup' => variable_get('rr_toolkit_images_text', ''),
        '#suffix' => '',
      );
      break;
    case 'rr_toolkit_templates':
      $block['content'] = array(
        '#type' => 'markup',
        '#markup' => variable_get('rr_toolkit_templates_text', ''),
        '#suffix' => '',
      );
      break;
    case 'rr_toolkit_types':
      $block['content'] = _rr_toolkits_types_content();
      break;
  }

  return $block;
}

/**
 * Implements hook_block_configure().
 */
function rr_toolkits_blocks_block_configure($delta = '') {
  $form = array();

  switch ($delta) {
    case 'rr_toolkit_images':
      // Text field form element
      $form['rr_toolkit_images'] = array(
        '#type' => 'text_format',
        '#title' => t('Enter content here.'),
        '#default_value' => variable_get('rr_toolkit_images_text', ''),
      );
      break;
    case 'rr_toolkit_templates':
      // Text field form element
      $form['rr_toolkit_templates'] = array(
        '#type' => 'text_format',
        '#title' => t('Enter content here.'),
        '#default_value' => variable_get('rr_toolkit_templates_text', ''),
      );
      break;
  }

  return $form;
}

/**
 * Implements hook_block_save().
 */
function rr_toolkits_blocks_block_save($delta = '', $edit = array()) {
  switch ($delta) {
    case 'rr_toolkit_images':
      // Saving the WYSIWYG text
      variable_set('rr_toolkit_images_text', $edit['rr_toolkit_images']['value']);
      break;
    case 'rr_toolkit_templates':
      // Saving the WYSIWYG text
      variable_set('rr_toolkit_templates_text', $edit['rr_toolkit_templates']['value']);
      break;
  }
}

/**
 * Return a set of links in an item list.
 *
 * @see rr_toolkits_blocks_block_view()
 */
function _rr_toolkits_types_content() {
  return array(
    '#theme' => 'item_list',
    '#type' => 'ul',
    '#attributes' => array('class' => 'toolsType'),
    '#items' => array(
      l('Images', 'learn-educate/toolkits/images', array('attributes' => array('class' => 'toolsType_image'))),
      l('Articles & Fact Sheets', 'learn-educate/toolkits/articles', array('attributes' => array('class' => 'toolsType_article'))),
      l('Ad & Print Templates', 'learn-educate/toolkits/templates', array('attributes' => array('class' => 'toolsType_template'))),
    ),
  );
}